### ISSUE TITLE
[Bug]: Outdated, no longer working?

### ISSUE THREAD

**Issue by asheroto** [kerhub/issue-forms-creator#128]
### Description

Hi there, I think GitHub may have changed their template styles and this generator no longer works. Although this may be a GitHub bug?

I see that this generator creates templates such as this...

![image](https://github.com/kerhub/issue-forms-creator/assets/49938263/258c9de8-e956-4dcb-a3dd-7553b9ba8d97)

but when I insert that, GitHub doesn't pick it up (I used Bug Report)

![image](https://github.com/kerhub/issue-forms-creator/assets/49938263/a0bbcde0-3834-421b-8206-f7855fc0ec4f)

When I added the `--` above and below the header like so..

![image](https://github.com/kerhub/issue-forms-creator/assets/49938263/8b201a4b-5f35-4d2c-b0db-fa076d0993ab)

then I got this warning...

![image](https://github.com/kerhub/issue-forms-creator/assets/49938263/c969371e-b8f7-4b99-b53c-275e55623c10)

so I changed "description" to "about", but then it still doesn't pick up the rest of it in the new template...

![image](https://github.com/kerhub/issue-forms-creator/assets/49938263/a651c302-2e06-47b4-8cf0-5efdea64879d)

The weird thing is, your syntax matches here:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Maybe I'm missing something or there's a GitHub bug with my repo?

**Comment by asheroto** [comment]
Here's an example of what I generated:
https://gist.github.com/asheroto/796684e8fc4a79cfdf88e8d74decc6ed

**Comment by asheroto** [comment]
Nevermind! Goof! Haha. Used the wrong extension. Sorry for wasting your time, carry on and thanks for the great tool. 😊

Templates with checkboxes, input boxes, textarea, etc, need to have a `yml` extension.

**Comment by geromegrignon** [comment]
Hi @asheroto thanks for the kind words!

Indeed the previous **template** feature was working with .md file
