### ISSUE TITLE
[Bug]: The URL listed in the about section apears to be down/broken.

### ISSUE THREAD

**Issue by VantorreWannes** [kerhub/issue-forms-creator#130]
### Description

I've recently started a new project and wanted to use this tool again to generate some awesome issue templates.
Sadly whenever i surf to [the URL listed in the about section]([issue-forms-creator.netlify.app/](https://issue-forms-creator.netlify.app/)) it returns a `404` error.
![image](https://github.com/user-attachments/assets/07382886-3307-4a66-9baf-d7f58c7b8f22)

### Minimal Reproduction

browse to [https://issue-forms-creator.netlify.app/](https://issue-forms-creator.netlify.app/) and find out for yourself.

Specs:
- Browser: Firefox
- OS: Arch Linux
- Region: Belgium

### Site Not Found

Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.

[Back to our site](https://issue-forms-creator.netlify.app/)

---

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

Netlify Internal ID: `01J44G98FP5E6CPQD4W0FXWHQK`

**Comment by geromegrignon** [comment]
Hi, that's fixed.
Thanks for the report!
