### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 3kh0** [kerhub/issue-forms-creator#17]
### Description

When I input a valid GitHub Repo URL, it says it is invalid. I am inputting `https://github.com/3kh0/3kh0.github.io` but it says invalid.

### Minimal Reproduction

Input `https://github.com/3kh0/3kh0.github.io` into the Github repository url field

### Exception or Error

![image](https://user-images.githubusercontent.com/58097612/159035803-6000fcfd-f9a7-4884-b862-f0783faf14fc.png)

![image](https://user-images.githubusercontent.com/58097612/159035864-2e551f9a-6e1b-428d-b8f6-c115fdfe002b.png)

**Comment by geromegrignon** [comment]
Hi, thanks for the report.

I had this issue in mind for ages but could not find the time to fix it.
It's fixed now! 🚀

**Comment by 3kh0** [comment]
Thank you so much for fixing this!!! You will get my ⭐!
