### ISSUE TITLE
[Bug]: assignee can't be removed once added

### ISSUE THREAD

**Issue by lrstanley** [kerhub/issue-forms-creator#19]
### Description

After adding an assignee using the form builder, if you then remove that assignee, they aren't actually removed (both in the UI, and when you generate the YAML).

### Minimal Reproduction

1. Go to https://issue-forms-creator.app/new
2. Add a random user
3. Remove the random user
4. see right side, user still exists
5. Generate YAML, and inspect for the `assignee` field still being populated.

**Comment by geromegrignon** [comment]
Hi, thanks for reporting this issue.

It's now fixed!
